# Generated by Django 6.0.2 on 2026-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('average_level', models.IntegerField()),
                ('raw_level', models.IntegerField(default=0)),
                ('status', models.CharField(default='Quiet', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
