# Generated by Django 6.0.2 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.CharField(default="default", max_length=32, unique=True)),
                ("quiet_threshold", models.IntegerField(default=800)),
                ("medium_threshold", models.IntegerField(default=1500)),
                ("loud_threshold", models.IntegerField(default=2500)),
                ("buzzer_on_loud", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Configuration",
                "verbose_name_plural": "Device Configuration",
            },
        ),
    ]