# Generated by Django 6.0.2 on 2026-04-24 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deviceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('ends_at', models.DateTimeField(editable=False)),
                ('quiet_threshold', models.IntegerField(default=800)),
                ('medium_threshold', models.IntegerField(default=1500)),
                ('high_threshold', models.IntegerField(default=2500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='noiselog',
            name='device_id',
            field=models.CharField(default='esp32-luminaquiet-01', max_length=64),
        ),
        migrations.AddField(
            model_name='noiselog',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='noiselog',
            name='quiet_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noiselog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.session'),
        ),
    ]
