# Generated by Django 6.0.2 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_session_noiselog_device_id_noiselog_previous_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noiselog",
            name="sensor_values",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
