# Generated by Django 6.0.2 on 2026-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deviceconfig_calibration_coefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiselog',
            name='db_level',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
